# Generated by Django 4.2 on 2025-05-11 12:15

from django.db import migrations
import pgvector.django.vector
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("adminchat", "0001_initial"),
    ]

    operations = [
        # 1. Asegurar que la extensión pgvector está instalada
        VectorExtension(),

        # 2. Eliminar la columna JSON existente
        migrations.RemoveField(
            model_name='embedding',
            name='vector',
        ),
        # 3. Añadir la nueva columna vector
        migrations.AddField(
            model_name="embedding",
            name="vector",
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
