# Generated by Django 4.2 on 2025-04-26 17:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("adminchat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("llm_model_name", models.CharField(default="gpt-4", max_length=100)),
                (
                    "embedding_model_name",
                    models.CharField(default="text-embedding-ada-002", max_length=100),
                ),
                (
                    "sentiment_model_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "intent_model_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("search_top_k", models.IntegerField(default=5)),
                ("search_min_similarity", models.FloatField(default=0.75)),
                ("generation_temperature", models.FloatField(default=0.7)),
                ("generation_top_p", models.FloatField(default=0.9)),
                ("generation_top_k", models.IntegerField(default=50)),
                ("generation_frequency_penalty", models.FloatField(default=0.0)),
                ("generation_presence_penalty", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_settings",
                        to="adminchat.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Settings",
                "verbose_name_plural": "Bot Settings",
                "db_table": "chat_botsettings",
            },
        ),
        migrations.CreateModel(
            name="BotTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("greeting", "Saludo"),
                            ("farewell", "Despedida"),
                            ("sales", "Venta"),
                            ("support", "Soporte"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt_template", models.TextField()),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("top_p", models.FloatField(blank=True, null=True)),
                ("top_k", models.IntegerField(blank=True, null=True)),
                ("frequency_penalty", models.FloatField(blank=True, null=True)),
                ("presence_penalty", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_templates",
                        to="adminchat.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Template",
                "verbose_name_plural": "Bot Templates",
                "db_table": "chat_bottemplate",
                "unique_together": {("business", "name")},
            },
        ),
    ]
